accounts/urls.py
from django.urls import path
from . import views
# ログイン用のviewをインポート
from django.contrib.auth import views as auth_views
app_name = 'accounts'
urlpatterns = [
    path('signup/',views.SignUpView.as_view(), name='signup'),
    path('signup_success/',views.SignUpSuccessView.as_view(), name='signup_success'),
    path("signin/",auth_views.LoginView.as_view(template_name='signin.html'),name='signin'),
    path('signout/',auth_views.LogoutView.as_view(template_name='signout.html'),name='signout'),
    path('user-detail/<int:pk>/',views.UserDetailView.as_view(),name='userdetail'),
    path('user-update/<int:pk>/',views.UserUpdateView.as_view(),name='userupdate'),
    path('user-delete/<int:pk>',views.PhotoDetleteView.as_view(),name='delete')
]

stock/urls.py
from django.urls import path
from . import views

app_name = 'stock'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('product_add/',views.AddView.as_view(),name='add'),
    path('catogory/<int:category>',views.CategoryView.as_view(),name='category'),
    path('stock',views.StockView.as_view(),name='stock')
]

stockproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('stock.urls')),
    path('',include('accounts.urls')),
    path('',include('contact.urls'))
]

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class StockUser(AbstractUser):
    pass

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import StockUser

class StockUserCreationForm(UserCreationForm):
    class Meta:
        model = StockUser
        fields = ('username','email','password1','password2')

class StockUserUpdatesForm(ModelForm):
    class Meta:
        model = StockUser
        fields = ('last_name','first_name','email')

class StockUserDetailForm(ModelForm):
    class Meta:
        model = StockUser
        fields = ('username','last_name','first_name','email')

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView, UpdateView, DetailView, DeleteView
from .forms import StockUserCreationForm, StockUserUpdatesForm, StockUserDetailForm
from django.urls import reverse_lazy
from .models import StockUser

class SignUpView(CreateView):
    form_class = StockUserCreationForm
    template_name = "signup.html"
    success_url = reverse_lazy('accounts:signup_success')

    def form_valid(self, form) :
        
        user = form.save()
        self.object = user

        return super().form_valid(form)

class SignUpSuccessView(TemplateView):
    template_name = "signup_success.html"

class UserUpdateView(UpdateView):
    model = StockUser
    fields = ('last_name','first_name','email')
    template_name= 'userupdate.html'
    success_url = reverse_lazy('stock:stock' )

class UserDetailView(DetailView):
    model = StockUser
    form_class = StockUserDetailForm
    template_name = 'userdetail.html'


class PhotoDetleteView(DeleteView):
    template_name = 'userdelete.html'
    model = StockUser
    success_url = reverse_lazy('stock:index')

accounts/templates/password_reset.html
<!-- ベーステンプレートを適用する-->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する-->
{% block title %}Reset password{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム-->
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の上下パディングはpy-4-->
          <div class="col py-4">
            <hr>
            <h3>パスワードをリセットしますか?</h3>
            <p>
              登録済みのメールアドレスを入力してください。
              パスワードリセットのリンクを記載したメールをすぐにお届けします。
            </p>
            <br>
            <!-- メール送信のためのフォームを配置-->
            <form action="" method="POST" class="text-center">
              {% csrf_token %}
              <!-- formに格納されているインプットボックスとラベルを出力-->
              {{form}}
              <!-- 送信ボタン -->
              <input type="submit" value="メールを受け取る" /><br>
            </form>
            <br>
            <!-- トップページへのリンク-->
            <a href="{% url 'photo:index' %}">Photo Gallery</a>
            <hr>
          </dv>
        </dv>
      </dv>
      {% endblock %}

accounts/templates/password_reset_done.html
<!doctype html>
<html lang="ja">
  <head>
    <style>
      .pad{
        background-color: lavender;
        border: solid 2px;
        padding-top: 30px;
        padding-bottom: 50px;
        padding-left: 100px;
        margin-top: 50px;
        margin-right: 70px;
        margin-left: 70px;
      }
    </style>
  </head>

  <body>
    <div class="pad">
      <h2>パスワードがリセットされました。</h2>
      <p>
        Your Password has been set. You may go ahead and login
      </p>
      <br>
      <!-- トップページへのリンク-->
      <a href="{% url 'photo:stock' %}">トップページへ</a>
    </div>
  </body>
</html>

accounts/templates/password_reset_form.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- マージン、パディング、背景色を設定するCSSを定義 -->
    <style>
      .pad{
        background-color: lavender;
        border: solid 2px;
        padding-top: 30px;
        padding-bottom: 50px;
        padding-left: 100px;
        margin-top: 50px;
        margin-right: 70px;
        margin-left: 70px;
      }
    </style>
  </head>

  <body>
    <div class="pad">
      <h2>Photo Gallery</h2>
      <h4>
        新しいパスワードを2回入力してください。これにより、
        正しく入力できたことが確認されます。
      </h4>
      <br />
      <!-- フォームを配置-->
      <form action="" method="POST">
        {% csrf_token %}
        <!-- formに格納されている要素をすべてを出力 -->
        {{form}}
        <!-- パスワードリセットボタン-->
        <input type="submit" value="パスワードリセット"/>
      </form>
    </div>
  </body>
</html>

accounts/templates/password_reset_sent.html
<!-- ベーステンプレートを適用する-->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する-->
{% block title %}Send password reset{% endblock %}

      {% block contents %}
      <!-- 水平線-->
      <hr>
      <!-- Bootstrapのグリッドシステム-->
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-2を入れる
               列の上下パディングはpy-4-->
          <div class="col offset-2 py-4">
              <h5>パスワードのリセット手順をメールで送信しました。
                  メールはすぐに届きます。</h5>
              <br>
              <h6>
                メールが届かない場合は、登録済みのメールアドレスであるかを
                確認し、迷惑メールフォルダーも確認してみてください。</h6>
              <br>
              <!-- トップページへのリンク-->
              <a "{% url 'photo:index' %}">Photo Gallery</a>
          </dv>
        </dv>
      </dv>
      {% endblock %}

accounts/templates/signin.html
{% extends "base.html" %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

 {% block contents %} 

 {% include "stock_sideber.html" %}
  <body class="text-center">    
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <!-- ユーザー名とパスワードが一致しない場合のメッセージ -->
      {% if form.errors %}
        <p style="color: red">ユーザー名とパスワードが一致しません。</p>
      {% endif %}
      <!-- ログインのフォームを配置 -->
      <form method="post">
        {% csrf_token %}
        <!-- Bootstrapのロゴを表示 -->
        <!-- 「static/img/bootstrap-logo.svg」の読み込み -->
        <img class="mb-4">

        <h1 class="h3 mb-3 fw-normal">サインイン</h1>
        <!--
        <div class="form-floating">～</div>の2つのブロックを削除して
        以下に書き換え
        -->
        <!-- Usernameのラベル(非表示) -->
        <label for="Username" class="visually-hidden">
          User name</label>
        <!-- usernameの<input>タグを出力-->
        <!-- name属性の値はLoginViewで定義されているフィールド名username -->
        <input type="text"
               name="username"
               id="id_username"
               maxlength="150"
               autocapitalize="none"
               autocomplete="username"
               class="form-control"
               placeholder="ユーザー名"
               required autofocus>
        <!-- Passwordのラベル(非表示) -->
        <label for="Password" class="visually-hidden">
          Password</label>
        <!-- passwordの<input>タグを出力-->
        <!-- name属性の値はLoginViewで定義されているフィールド名password -->
        <input type="password"
               name="password"
               id="id_password"
               autocomplete="current-password"
               class="form-control"
               placeholder="パスワード"
               required autofocus>
        
        <!-- <button>～</button>を書き換えてログインボタンを配置 -->
            <input class="w-100 btn btn-lg btn-primary"
                   type="submit"
                   value="ログイン">
        
        <!-- パスワードリセットページのリンクテキスト -->
        <br><br>
        <p><a href="#">パスワードを忘れましたか?</a><p>
        <!-- ログイン直後のリダイレクト先(トップページ)のURLパターンを設定 -->
        <input type="hidden"
               name="next"
               value="{% url 'stock:index' %}">
      </form>
    </main> 
  </body>  
    {% endblock contents %}  

accounts/templates/signout.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Log out{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-4を入れる
               列の上下パディングはpy-4 -->
          <div class="col offset-4 py-4">

          <h3>サインアウトしました</h3>
          <!-- トップページのリンクテキスト -->
          <p><a href="{% url 'stock:index' %}">トップページへ</a><p>
      {% endblock %}

accounts/templates/signup.html
{% extends "base.html" %}

{% block title %}Sign up{% endblock title %}

    {% block contents %}

    <hr>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h3>サインアップ</h3>
                <form method = "post">
                    <!--クロスサイト系の攻撃を防止-->
                    {% csrf_token %}
                    {% for field in form %}
                     <p>
                        {{field.label_tag}}<br>
                        {{field}}
                        <!--備考のようなもの-->
                        {% if field.help_text %}
                            <small style="color: grey">{{field.help_text}}</small>
                        {% endif %}
                        {% for error in field.errors %}
                            <p style="color: red">{{error}}</p>
                        {% endfor %}
                     </p>
                    {% endfor %}
                    <p style="color:red">
                        メールアドレスはパスワードをリセットする際に必要になりますので、登録をお願いします
                    </p>
                    <input type="submit" value="Sign up">
                </form>
                <br>
                <p><a href="{% url "stock:index" %}">
                    登録をやめてトップページに戻る</a>
                </p>
            </div>
        </div>
    </div>
    {% endblock %}

accounts/templates/signup_success.html
{% extends "base.html" %}

{% block title %}Registaration Complete{% endblock title %}

{% block contents %}
<!--bootstrapのグリッドシステム-->
<div class="container">
    <!--行を配置-->
    <div class="row">
        <!--列の左右に余白offset-4を入れる
            列の上下パディングはpy-4-->
        <div class="col offset-4 py-4">
            <h3>新規作成が完了しました</h3>
            <p><a href={% url "accounts:signin" %}>ログインはこちら</a></p>
        </div>
    </div>
</div>
{% endblock contents %}

accounts/templates/userdelete.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}UerDelete{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <br>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-3を入れる -->
          <div class="col offset-3">
            <form method="POST">
              <br>
              <p>削除してもいいですか?</p>
              {% csrf_token %}
              <button class="btn btn-primary my-2"
                      type="submit">削除</button>
              <a href="{% url 'accounts:userdetail' user.pk %}"
                 class="btn btn-secondary my-2">キャンセル</a>
          </dv>
        </dv>
      </dv>
      {% endblock %}

accounts/templates/userdetail.html
{% extends "base.html" %}

{% block title %}アカウント設定{% endblock title %}

{% block contents %}
{% include "stock_sideber.html" %}


<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

<br>
<div class="container">
<!-- 行を配置 -->
<div class="row">
    <!-- 列の左右に余白offset-2を入れる -->
    <table class="table">
        <tbody>
            <tr>
                <th>ユーザー名</th>
                <td>{{ user.username }}</td>
            </tr>

            <tr>
                <th>メールアドレス</th>
                <td>{{ user.email}}</td>
            </tr>

            <tr>
                <th>姓</th>
                <td>{{ user.last_name }}</td>
            </tr>
            <tr>

                <th>名</th>
                <td>{{ user.first_name }}</td>
            </tr>
        </tbody>
    </table>

</dv>
    <div class="btn-group me-2">
    <a href={% url "accounts:userupdate" user.pk %}>変更</a>
  </div>
  <div>
    <a href={% url "accounts:delete" user.pk %}>削除</a>
  </div>
</dv>

</main>

{% endblock contents %}

accounts/templates/userupdate.html
{% extends "base.html" %}

{% block title %}アカウント設定{% endblock title %}

{% block contents %}
{% include "stock_sideber.html" %}


<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

<br>
<div class="container">
<!-- 行を配置 -->
<div class="row">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="更新">
    </form>
</dv>

</dv>

</main>

{% endblock contents %}