accounts/urls.py
from django.urls import path
from . import views
# ログイン用のviewをインポート
from django.contrib.auth import views as auth_views
app_name = 'accounts'
urlpatterns = [
    path('signup/',views.SignUpView.as_view(), name='signup'),
    path('signup_success/',views.SignUpSuccessView.as_view(), name='signup_success'),
    path("signin/",auth_views.LoginView.as_view(template_name='signin.html'),name='signin'),
    path('signout/',auth_views.LogoutView.as_view(template_name='signout.html'),name='signout'),
    path('user-detail/<int:pk>/',views.UserDetailView.as_view(),name='userdetail'),
    path('user-update/<int:pk>/',views.UserUpdateView.as_view(),name='userupdate'),
    path('user-delete/<int:pk>',views.PhotoDetleteView.as_view(),name='delete')
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('contact',views.ContactView.as_view(),name='contacts'),

]

stock/urls.py
from django.urls import path
from . import views

app_name = 'stock'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('product_add/',views.AddView.as_view(),name='add'),
    path('catogory/<int:category>',views.CategoryView.as_view(),name='category'),
    path('stock',views.StockView.as_view(),name='stock')
]

stockproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('stock.urls')),
    path('',include('accounts.urls')),
    path('',include('contact.urls'))
]

stock/models.py
from django.db import models
from accounts.models import StockUser
# ログイン中のユーザーを取得するフィールド
from django_currentuser.db.models import CurrentUserField

class Category(models.Model):
    category = models.CharField(
        verbose_name='カテゴリー',
        max_length=15
    )
    
    def __str__(self) :
        return self.category
    
# https://qiita.com/startours777/items/2a4e70ec85cc3e93a1ab
class Stocker(models.Model):
    user = models.ForeignKey(
        StockUser,
        verbose_name='ユーザ',
        on_delete= models.CASCADE
    )

    product = models.CharField(
        verbose_name='商品名',
        max_length=20,
    )
    category = models.ForeignKey(
        Category,
        verbose_name='カテゴリ',
        on_delete= models.PROTECT,
    )

    stock_quantity = models.IntegerField(
        verbose_name='在庫数',
    )

    
    create_date = models.DateTimeField(
        verbose_name="作成日時", 
        auto_now_add=True
        )

    
    update_date = models.DateTimeField(
        verbose_name="更新日時",
        auto_now=True,
        )

stock/forms.py
from django.forms import ModelForm
from .models import Stocker

class StockAddForm(ModelForm):
    class Meta:
        model = Stocker
        fields = ['product','stock_quantity','category']

stock/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, CreateView
from .models import Stocker, Category
from .forms import StockAddForm
from django.urls import reverse_lazy
from django.contrib import messages
from django.shortcuts import redirect

class IndexView(TemplateView):
    template_name = 'index.html'


class StockView(ListView):
    template_name ='stock.html'
    
    def get_queryset(self):
        user = Stocker.objects.filter(user=self.request.user).order_by('-update_date')
        return user


    def post(self, request):
        if "erase" in request.POST:
            stock_pks = request.POST.getlist('delete')
            Stocker.objects.filter(pk__in=stock_pks).delete()
            url = 'stock:index'

            
        return redirect(url)
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        # 2つ目のモデルを指定
        ctx["category"] = Category.objects.all()
        return ctx

    
class AddView(CreateView):
    form_class = StockAddForm
    template_name = 'product_add.html'
    success_url = reverse_lazy('stock:add')

    def form_valid(self, form):
        adddata = form.save(commit=False)
        adddata.user = self.request.user
        adddata.save()
        messages.success(self.request, '登録しました')
        return super().form_valid(form)
    

    
class CategoryView(ListView):
    template_name = 'index.html'
    def get_queryset(self):
        category_id = self.kwargs['category']
        # filter(フィールド名=id)で絞り込む
        categories = Stocker.objects.filter(category=category_id).order_by('update_date')
        return categories
    
    
    def post(self, request, category):
        if "erase" in request.POST:
            stock_pks = request.POST.getlist('delete')
            Stocker.objects.filter(pk__in=stock_pks).delete()
            url = 'stock:index'     
        return redirect(url)
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        # 2つ目のモデルを指定
        ctx["category"] = Category.objects.all()
        return ctx

stock/templates/index.html
{% extends "base.html" %}
{% block contents %}
{% if user.is_authenticated %}
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <main class="px-3">
      <h1>在庫管理丸くん</h1>
      <p class='lead'>現在{{user}}でログイン中です</p>
      <p class="lead">
        <a href={% url "accounts:signout" %} class="btn btn-lg btn-light fw-bold border-black ">ログアウト</a>        
      </p>
      <p class="lead">下のボタンをクリックで在庫を管理できます</p>
      <p class="lead">
        <a href={% url "stock:stock" %} class="btn btn-lg btn-light fw-bold border-black ">利用する</a>        
      </p>
  
    </main>
  </div>
{% else %}
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <main class="px-3">
      <h1>新規会員登録もしくはログイン</h1>
      <p class="lead">在庫管理丸くんを使うにはログインしてください<br>アカウントがない場合は会員登録してください</p>
      <p class="lead">
        <a href={% url "accounts:signup" %} class="btn btn-lg btn-light fw-bold border-black ">会員登録</a>
        <a href={% url "accounts:signin" %} class="btn btn-lg btn-light fw-bold border-black">ログイン</a>
      </p>
  
    </main>
  </div>

{% endif %}
  {% endblock contents %}

stock/templates/product_add.html
{% extends "base.html" %}

{% block title %}add{% endblock title %}

{% block contents %}
{% include "stock_sideber.html" %}


<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

<br>
<div class="container">
<!-- 行を配置 -->
<div class="row">
    <!-- 列の左右に余白offset-2を入れる -->
    <div class="col offset-2">
    <!-- ファイルをアップロードする場合は
            enctype="multipart/form-data"が必要 -->
    <form method="POST">
        {% csrf_token %}
        <table>
        <tr>
            <th>商品名</th>
            <td>{{ form.product }}</td>
        </tr>
        <tr>
            <th>数量</th>
            <td>{{ form.stock_quantity }}</td>
        </tr>
        <tr>
            <th>カテゴリ</th>
            <td>{{ form.category }}</td>
        </tr>
        </table>
        <hr>
        <button type="submit">追加</button>
    </form>        
    </dv>
    {% if messages %}
    <ul class="col offset-4">
    {% for message in messages %}
    <li {% if message.tags %}class="{{ message.tags }}"{% endif %}>
        {{message}}
    </li>
    {% endfor %}
</ul>
{% endif %}
</dv>

</dv>
<br>
<p><a href={% url "stock:stock" %}>戻る</a></p>

</main>

{% endblock contents %}

stock/templates/stock.html
{% extends "base.html" %}
{% block title %}在庫{% endblock title %}
{% block contents %}
{% include "stock_sideber.html" %}
{% include "stock_main.html" %}
{% endblock contents %}

stock/templates/stock_main.html
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">


  <div clas="row">
  {% if user.is_authenticated %}
  <h2>在庫</h2>
    <form action="" method="POST">
      <div class="btn-toolbar mb-2 mb-md-0">
        
        <div class="btn-group me-2">
          <button type="button" onclick="location.href={% url "stock:add" %}" class="btn btn-sm btn-outline-secondary">追加</button>
          <button type="submit" class="btn btn-sm btn-outline-secondary" name="erase">削除</button>
        </div>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center">絞り込み</h6>
        <from action="" method='POST'>
          <select name="choice1" id="id_choice1"onChange="location.href=value"class="btn btn-sm btn-outline-secondary dropdown-toggle d-flex align-items-center gap-1">
            <option value="{% url "stock:index" %}">-----</option> 
          {% for record in category %}
            <option  value="{% url "stock:category" record.id %}">{{record.category}}</option>
          {% endfor %}
          </select> 
        </from>
      </div>
      <div class="table-responsive small">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">商品名</th>
              <th scope="col">個数</th>
              <th scope="col">カテゴリ</th>
              <th scope="col">更新日</th>
            </tr>
          </thead>
          <tbody>
            {% for record in object_list %}
              <tr>
                <td><input type="checkbox" name="delete" value="{{ record.pk }}"></td>
                <td>{{record.product}}</td>
                <td>{{record.stock_quantity}}</td>
                <td>{{record.category}}</td>
                <td>{{record.create_date}}</td>
              </tr>
              {% endfor %}
              {% csrf_token %}
          </tbody>
        </table>
      </div>
    </fomr>
  </div>

  {% endif %}
</main>

stock/templates/stock_sideber.html
<div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
    <div class="offcanvas-lg offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="sidebarMenuLabel">Company name</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href={% url "stock:stock" %}>
              <svg class="bi"><use xlink:href="#house-fill"/></svg>
              Stock
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href={% url "contact:contacts" %}>
              <svg class="bi"><use xlink:href="#file-earmark"/></svg>
              Contact
            </a>
          </li>
          {% comment %} <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
              <svg class="bi"><use xlink:href="#cart"/></svg>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
              <svg class="bi"><use xlink:href="#people"/></svg>
              Customers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
              <svg class="bi"><use xlink:href="#graph-up"/></svg>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
              <svg class="bi"><use xlink:href="#puzzle"/></svg>
              Integrations
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase">
          <span>Saved reports</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <svg class="bi"><use xlink:href="#plus-circle"/></svg>
          </a>
        </h6>
        <ul class="nav flex-column mb-auto">
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
              <svg class="bi"><use xlink:href="#file-earmark-text"/></svg>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
              <svg class="bi"><use xlink:href="#file-earmark-text"/></svg>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
              <svg class="bi"><use xlink:href="#file-earmark-text"/></svg>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
              <svg class="bi"><use xlink:href="#file-earmark-text"/></svg>
              Year-end sale
            </a>
          </li>
        </ul>

        <hr class="my-3">
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase"> {% endcomment %}
          <span>アカウント</span>
        </h6>
        <ul class="nav flex-column mb-auto">

            {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="{% url "accounts:userdetail" user.pk%}">
              <svg class="bi"><use xlink:href="#gear-wide-connected"/></svg>
              詳細
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="{% url "accounts:signout" %}">
              <svg class="bi"><use xlink:href="#door-closed"/></svg>
              サインアウト
            </a>
          </li>
         {% else %}
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="{% url "accounts:signup" %}">
              <svg class="bi"><use xlink:href="#door-closed"/></svg>
              新規作成
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="{% url "accounts:signin" %}">
              <svg class="bi"><use xlink:href="#door-closed"/></svg>
              サインイン
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>